#ifndef _B98BBE3C_0CFF_4BDA_AA18_0F599CF52724_
#define _B98BBE3C_0CFF_4BDA_AA18_0F599CF52724_

#include <poclass.h>

#define STRINGIZE(x) x, #x

struct KNOWN_IOCTL {
    ULONG Code;
    PCHAR CodeAsString;
} DetectedIoctl[] = {
    { STRINGIZE(IOCTL_THERMAL_QUERY_INFORMATION) },
    { STRINGIZE(IOCTL_THERMAL_READ_TEMPERATURE) },
    { STRINGIZE(IOCTL_THERMAL_READ_POLICY) },
    { STRINGIZE(IOCTL_GET_SYS_BUTTON_CAPS) },
    { STRINGIZE(IOCTL_GET_SYS_BUTTON_EVENT) },
    { STRINGIZE(IOCTL_THERMAL_SET_COOLING_POLICY) },
    { STRINGIZE(IOCTL_RUN_ACTIVE_COOLING_METHOD) }
};

#define STACK_CAPTURE 32

C_ASSERT(sizeof(PVOID) == 8);

#define HARDWAREID_FORMAT_WITH_SEGMENT L"0x%p @%04X:%02X:%02X.%u="
#define HARDWAREID_PREFIX_WITH_SEGMENT L"0xFFFFA6833C710D50 @0000:00:1F.7="

#define HARDWAREID_FORMAT_WO_SEGMENT L"0x%p @%02X:%02X.%u="
#define HARDWAREID_PREFIX_WO_SEGMENT L"0xFFFFA6833C710D50 @00:1F.7="

#endif
